<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-F2UU26L" name="neotech.ProductClientTest" tests="7" failures="0" timestamp="2021-01-15T16:43:46 IST" time="2.860" errors="1">
  <testcase name="testGetBadRequest" time="0.133" classname="neotech.ProductClientTest"/>
  <system-out/>
  <testcase name="testGetProduct" time="0.363" classname="neotech.ProductClientTest"/>
  <system-out/>
  <testcase name="testUpdateProduct" time="0.270" classname="neotech.ProductClientTest"/>
  <system-out/>
  <testcase name="testAddProduct" time="0.037" classname="neotech.ProductClientTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method neotech.ProductClientTest.testAddProduct() didn&#039;t finish within the time-out 10">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method neotech.ProductClientTest.testAddProduct() didn't finish within the time-out 10
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$51/3224332.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testAddProduct -->
  <system-out/>
  <testcase name="testGetAllProducts" time="1.946" classname="neotech.ProductClientTest"/>
  <system-out/>
  <testcase name="testGetRequestNotFound" time="0.111" classname="neotech.ProductClientTest"/>
  <system-out/>
  <testcase name="testDeleteProduct" classname="neotech.ProductClientTest">
    <skipped/>
  </testcase> <!-- testDeleteProduct -->
  <system-out/>
</testsuite> <!-- neotech.ProductClientTest -->
